// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxA3zSBvE58GfFbfR9aPbALToEKqofpoc',
    appId: '1:780367220728:web:ff9b1e8cf23c60bfba100d',
    messagingSenderId: '780367220728',
    projectId: 'hospisolve',
    authDomain: 'hospisolve.firebaseapp.com',
    storageBucket: 'hospisolve.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5LMlDtT1O-tFM6gktj8d3QDHx674E-XY',
    appId: '1:780367220728:android:cbf798667790e856ba100d',
    messagingSenderId: '780367220728',
    projectId: 'hospisolve',
    storageBucket: 'hospisolve.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR1SYPsGrsPH2TmdAF4NNOX1po0ZIRBIg',
    appId: '1:780367220728:ios:7fb9f8cc8bf48ce3ba100d',
    messagingSenderId: '780367220728',
    projectId: 'hospisolve',
    storageBucket: 'hospisolve.appspot.com',
    iosBundleId: 'com.hospisolve.hospisolve',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR1SYPsGrsPH2TmdAF4NNOX1po0ZIRBIg',
    appId: '1:780367220728:ios:125ccd39ca0d8e99ba100d',
    messagingSenderId: '780367220728',
    projectId: 'hospisolve',
    storageBucket: 'hospisolve.appspot.com',
    iosBundleId: 'com.hospisolve.hospisolve.RunnerTests',
  );
}
